apiVersion: v1
kind: Service
metadata:
  name: influx-svc
spec:
  selector:
    app: influx
  ports:
  - protocol: TCP
    name: influx
    port: 8086
    targetPort: 8086
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-deployment
spec:
  selector:
    matchLabels:
      app: influx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influx
    spec:
      containers:
      - image: influx_image
        imagePullPolicy: Never
        name: influx
        ports:
        - containerPort: 8086
          name: influx
        volumeMounts:
        - name: influx-persistent-storage
          mountPath: /root/.influxdb/wal/
      volumes:
      - name: influx-persistent-storage
        persistentVolumeClaim:
          claimName: influx-pv-claim